### ISSUE TITLE
静态目录static没法引入

### ISSUE THREAD

**Issue by Alvin-Liu** [bluefox1688/vue-cli-multi-page#2]
有些文件，比如一些图片我想放在static目录，但是好像不能在module页面中引入

**Comment by bluefox1688** [comment]
理论上static里都可以放的，你现在是碰到什么问题呢

**Comment by Alvin-Liu** [comment]
官方的vue-cli是可以直接用'static/img/test.jpg'这种方式引入根目录下的static中文件的，不过我在你的vue-cli-multi-page中好像没办法引入，它会跑到‘src\module\welcome‘里面去找static(我用welcome做的测试)。不知道用什么方式，能给个例子吗

**Comment by LianyForWeb** [comment]
也遇到同样的问题 发现是路径有误static\img/test.jpg 这个形式

**Comment by bluefox1688** [comment]
如果是直接在当前文件夹使用的话，都要先import 才可以使用。
`
//例如
import Banner from './banner.jpg';
`

**Comment by LianyForWeb** [comment]
我把图片放在asset下面，但是不管我怎么设置路径，都把/替换成\



发自我的小米手机在 蓝狐 <notifications@github.com>，2016年9月18日 下午3:02写道：如果是直接在当前文件夹使用的话，都要先import 才可以使用。

//例如
import Banner from './banner.jpg';


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bluefox1688/vue-cli-multi-page","title":"bluefox1688/vue-cli-multi-page","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bluefox1688/vue-cli-multi-page"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bluefox1688 in #2: 如果是直接在当前文件夹使用的话，都要先import 才可以使用。\r\n`\r\n//例如\r\nimport Banner from './banner.jpg';\r\n`"}],"action":{"name":"View Issue","url":"https://github.com/bluefox1688/vue-cli-multi-page/issues/2#issuecomment-247830236"}}}

**Comment by Moerslion** [comment]
把路径该成  "../../assets/logo.png"  就可以了

**Comment by LianyForWeb** [comment]
已修复,需要对path.join做下兼容处理,==>path.posix.join

**Comment by InTwoDisease** [comment]
坑啊。。。。

**Comment by bluefox1688** [comment]
现在已经上线2.0，您可以体验试试
